language: c

os:
  - linux
  - osx

sudo: false # only for faster builds

git:
    submodules: false

compiler:
  - clang
  - gcc

before_install:
  - git submodule update --init
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 && rvm get stable; fi

install:
    - make

before_script:
    - cd .. && git clone https://github.com/sstephenson/bats.git && cd bats && export PATH=$PATH:$PWD/bin/ && cd ../21-42sh

script:
  - ./tests/tests.sh

after_success:
  - make fclean

notifications:
  email:
    recipients:
      - jlasne@student.42.fr
    on_success: change
    on_failure: always
  slack:
    rooms:
      - mrchapeau:2e9nZEItuNS5mFwMM0CBYYEF#github-travis
