language: c

sudo: false # only for faster builds

git:
    submodules: false

compiler:
  - clang
  - gcc

before_install:
    - sed -i 's/https:\/\/github.com\//git@github.com:/'.gitmodules
    - git submodule update --init
    - cd libcbc && sed -i 's/https:\/\/github.com\//git@github.com:/' .gitmodules && git submodule update --init && cd ..

script:
  - make

after_success:
  - make fclean
