language: c

os:
  - linux
  - osx

sudo: false # only for faster builds

git:
    submodules: false

compiler:
  - clang
  - gcc
  
addons:
  apt:
    packages:
    - build-essential


before_install:
    - export LOCAL="$(mktemp --directory --tmpdir=${TMPDIR:/tmp} local.bin.XXXXXX)"
    - curl -L http://downloads.sourceforge.net/zsh/zsh-5.0.7.tar.gz | tar zx
    - cd zsh-5.0.7
    - ./configure --prefix=$LOCAL
    - make
    - make install
    - cd -
    - export PATH="$LOCAL/bin:$PATH"
    - sed -i.bak 's/https:\/\/github.com\//git@github.com:/' .gitmodules
    - rm .gitmodules.bak
    - git submodule update --init
    - cd libcbc && sed -i.bak 's/https:\/\/github.com\//git@github.com:/' .gitmodules && rm .gitmodules.bak && git submodule update --init && cd ..
    - cd .. && git clone https://github.com/sstephenson/bats.git && cd bats && export PATH=$PATH:$PWD/bin/ && cd ../21-42sh

script:
  - make NOERR=yes
  - ./tests/tests.sh

after_success:
  - make fclean

notifications:
  email:
    recipients:
      - jlasne@student.42.fr
      - gpouyat@student.42.fr
    on_success: change
    on_failure: always
  slack:
    rooms:
      - mrchapeau:2e9nZEItuNS5mFwMM0CBYYEF#github-travis
